'use client';
import {useState} from 'react';
import {Check,Save,History,UserRound} from 'lucide-react';
import {Finding,User} from '../models';
import {canReviewFindings} from '../permissions';
import {findingService,findingStatuses,riskLabels} from '../services/findingService';
import {Badge,Choice} from '../components/controls';
import ObservationEvidence from './ObservationEvidence';
export function RiskRating({risk}:{risk:number}){return <span className="risk-rating" aria-label={`${riskLabels[risk-1]} risk, ${risk} of 5`}><span className="risk-squares" aria-hidden="true">{[1,2,3,4,5].map(n=><i key={n} className={n<=risk?'filled risk-'+risk:''}/>)}</span><span>{riskLabels[risk-1]}</span></span>}
export default function ObservationDetail({finding:f,user,onSaved}:{finding:Finding;user:User;onSaved:(f:Finding)=>void}) {
  const [status,setStatus]=useState(f.status),[risk,setRisk]=useState(String(f.risk)),[remarks,setRemarks]=useState(f.remarks),[assignee,setAssignee]=useState(f.assignee),[message,setMessage]=useState(''),[saving,setSaving]=useState(false);
  const editable=canReviewFindings(user);
  async function save(){setSaving(true);setMessage('');try{const result=await findingService.review(user,f.projectId,f.id,{status,risk:Number(risk),remarks,assignee});onSaved(result);setMessage('Review saved.');}catch(e){setMessage((e as Error).message);}finally{setSaving(false)}}
  return <><div className="observation-metadata"><span><b>{f.id}</b> · {f.assetId}</span><span>{f.projectId} / {f.block} / Row {f.row}</span><span>{f.date} · {f.time} UTC</span><Badge>{f.status}</Badge></div><div className="observation-detail-grid"><ObservationEvidence key={f.projectId+f.id} finding={f}/><section className="section-card observation-review"><div className="card-heading"><h2>Observation & action</h2><Badge>{f.severity}</Badge></div><div className="review-content"><h3>{f.type}</h3><p>{f.description}</p><div className="recommendation"><span>RECOMMENDATION</span><p>{f.recommendation}</p></div><div className="review-confidence"><span>Detection confidence <b>{f.confidence}%</b></span><span>Risk rating <RiskRating risk={f.risk}/></span></div><div className="review-form"><label>Status{editable?<Choice label="Observation status" value={status} onChange={setStatus} options={findingStatuses.map(value=>({value,label:value}))}/>:<Badge>{f.status}</Badge>}</label><label>Risk rating{editable?<Choice label="Observation risk rating" value={risk} onChange={setRisk} options={riskLabels.map((label,i)=>({value:String(i+1),label}))}/>:<RiskRating risk={f.risk}/>} </label><label className="full">Assigned to<input aria-label="Observation assignee" value={assignee} maxLength={100} readOnly={!editable} onChange={e=>setAssignee(e.target.value)}/></label><label className="full">Remarks<textarea aria-label="Observation remarks" value={remarks} maxLength={2000} readOnly={!editable} placeholder={editable?'Record inspection notes or the corrective action taken…':'No remarks recorded.'} onChange={e=>setRemarks(e.target.value)}/></label></div>{editable?<div className="review-save"><button className="primary" disabled={saving} onClick={()=>void save()}><Save size={15}/>{saving?'Saving…':'Save review'}</button><span>Demo changes last for this page session.</span></div>:<p className="read-only-note"><UserRound size={15}/>Client access · Reviews are updated by your inspection team.</p>}{message&&<p className="review-message" role="status"><Check size={15}/>{message}</p>}</div></section></div><section className="section-card observation-history"><div className="card-heading"><h2><History size={16}/>Review history</h2><span className="muted">{f.history.length} events</span></div>{[...f.history].reverse().map((event,i)=><div className="history-event" key={event.at+i}><span className="activity-pin"/><div><b>{event.action}</b><p>{event.remarks||'No additional remarks.'}</p><small>{event.actor} · {event.at.replace('T',' ').slice(0,19)} UTC</small></div></div>)}</section></>;
}
