'use client';
import {Project,User} from '../models';
import {Radio,ArrowUpRight,Sun,CheckCheck,Clock3} from 'lucide-react';
import {Badge,Meter} from '../components/controls';
import {permissions} from '../permissions';
export function SolarSummary({project:p}:{project:Project}){return <div className="stat-grid">{[['Project area',p.area,'Acres surveyed'],['Solar panels',p.panels.toLocaleString(),'Across 6 blocks'],['Inverters',48,'All registered'],['Structures','1,250','Mounting structures'],['Inspected',p.inspected.toLocaleString(),`${(100*p.inspected/p.panels).toFixed(1)}% of total panels`],['Open findings',p.openFindings,'Requires review']].map(([label,value,sub],i)=><div className={'stat '+(i===5?'findings-stat':'')} key={label}><span>{label}</span><strong>{value}</strong><small>{sub}</small></div>)}</div>}
export function InspectionProgress({project:p}:{project:Project}){const percent=100*p.inspected/p.panels;return <section className="section-card progress-card"><div className="card-heading"><h2>Inspection progress</h2><CheckCheck size={17}/></div><div className="ring-wrap"><div className="progress-ring" style={{background:`conic-gradient(#139b83 ${percent}%,#edf2f4 0)`}}><div><strong>{percent.toFixed(1)}<small>%</small></strong><span>Inspection complete</span></div></div></div><div className="progress-counts"><span><i className="legend-dot teal"/>Inspected <b>{p.inspected.toLocaleString()}</b></span><span><i className="legend-dot gray"/>Pending <b>{(p.panels-p.inspected).toLocaleString()}</b></span></div><div className="progress-foot"><CheckCheck size={15}/>{p.status==='Completed'?'All panels inspected':`${(p.panels-p.inspected).toLocaleString()} panels remaining`}</div></section>}
export function FindingsSummary({project:p}:{project:Project}){return <section className="section-card"><div className="card-heading"><h2>Findings by severity</h2><Badge>{p.openFindings+' open'}</Badge></div><div className="severity-bars">{[['Critical',8,'#d06664'],['High',34,'#e6a262'],['Medium',52,'#e4c271'],['Low',32,'#73a6b3']].map(([label,count,color])=><div key={label}><span>{label}<b>{p.openFindings===0?0:Math.round(Number(count)*p.openFindings/126)}</b></span><div className="bar-track"><div style={{width:(p.openFindings?Number(count)/52*100:0)+'%',background:String(color)}}/></div></div>)}</div></section>}
export default function SolarOverview({user,project:p,navigate,children}:{user:User;project:Project;navigate:(view:string,id?:string)=>void;children?:React.ReactNode}){return <><SolarSummary project={p}/><div className="overview-grid"><section className="section-card map-card"><div className="card-heading"><div><h2>Site overview</h2><p>{p.location} · Mock geographic data</p></div><button className="text-link" onClick={()=>navigate('map',p.id)}>Explore map <ArrowUpRight size={14}/></button></div>{children??<div className="map-placeholder"><Sun size={30}/><span>Solar survey area · {p.area} acres</span></div>}</section><InspectionProgress project={p}/></div><div className="overview-bottom"><FindingsSummary project={p}/><section className="section-card"><div className="card-heading"><h2>Latest inspection</h2><Badge>Completed</Badge></div><div className="latest-flight"><span className="flight-icon"><Sun size={22}/></span><div><h3>FLT-{p.id}-024</h3><p>18 Sep 2026 · DJI Matrice 350 RTK</p></div></div><div className="flight-numbers"><span><b>18.4 km</b>Distance covered</span><span><b>42 min</b>Flight duration</span><span><b>2,840</b>Panels inspected</span></div><button className="wide-link" onClick={()=>navigate('flights',p.id)}>View flight history <ArrowUpRight size={15}/></button></section><section className="section-card activity"><div className="card-heading"><h2>Inspection activity</h2><Clock3 size={16}/></div>{[['Inspection completed','Block C · 2,840 panels inspected','10:42 AM'],['Findings ready for review','34 observations from today’s flight','10:45 AM'],['Report generated','September inspection summary','11:00 AM']].map(([a,b,c])=><div className="activity-item" key={a}><span className="activity-pin"/><div><b>{a}</b><p>{b}</p><small>{c}</small></div></div>)}</section></div>{permissions(user).live&&<div className="live-banner"><div className="row"><Radio size={22}/><div><b>Your next perspective is live</b><p>Follow a simulated flight and watch the inspection unfold.</p></div></div><button className="primary" onClick={()=>navigate('simulation',p.id)}>Open flight simulator <ArrowUpRight size={16}/></button></div>}<div className="sr-only"><Meter value={100*p.inspected/p.panels}/></div></>}
