'use client';
import {useState} from 'react';
import {Radio,Video,Search,Download} from 'lucide-react';
import Image from 'next/image';
import {Project,User} from '../models';
import {mediaService} from '../services/mediaService';
import {Choice,Badge} from '../components/controls';
import VideoPlayer from '../components/VideoPlayer';
export default function Streaming({user,project,recorded=false}:{user:User;project:Project;recorded?:boolean}) {
  const clips=mediaService.list(user,project.id),live=mediaService.live(user,project.id);
  const [block,setBlock]=useState('all'),[date,setDate]=useState('all'),[search,setSearch]=useState(''),[selectedId,setSelectedId]=useState(clips[0]?.id??'');
  const filtered=clips.filter(c=>(block==='all'||c.block===block)&&(date==='all'||c.date===date)&&[c.id,c.title,c.flightId].join(' ').toLowerCase().includes(search.toLowerCase()));
  const selected=filtered.find(c=>c.id===selectedId)??filtered[0];
  if(!recorded)return live?<><div className="stream-header"><div className="row"><span className="stream-icon"><Radio size={23}/></span><div><h2>Live streaming</h2><p>A simple video view of the current inspection.</p></div></div><Badge>Demo feed</Badge></div><section className="section-card"><div className="card-heading"><div><h2>{project.name} · {live.block}</h2><p>{live.drone} · {live.flightId}</p></div><span className="muted">SIMULATED STREAM</span></div><VideoPlayer source={live.source} poster={live.poster} title="Solar inspection · demo feed" loop/></section><div className="stream-details"><span><b>Project</b>{project.id}</span><span><b>Area</b>{live.block}</span><span><b>Camera</b>RGB / thermal example</span><span><b>Source</b>Looping demo video</span></div></>:<div className="empty">No stream is available for this project.</div>;
  return <><div className="stream-header"><div className="row"><span className="stream-icon"><Video size={23}/></span><div><h2>Recorded footage</h2><p>Choose a saved inspection record and review its video.</p></div></div><span className="muted">{filtered.length} demo recordings</span></div><div className="observation-filterbar"><div className="search"><Search size={16}/><input aria-label="Search recorded footage" placeholder="Search flight, video, or block…" value={search} onChange={e=>setSearch(e.target.value)}/></div><Choice label="Recorded footage block" value={block} onChange={setBlock} options={[{value:'all',label:'All blocks'},...['A','B','C','D','E','F'].map(b=>({value:'Block '+b,label:'Block '+b}))]}/><Choice label="Recorded footage date" value={date} onChange={setDate} options={[{value:'all',label:'All dates'},...['2026-09-18','2026-09-15','2026-09-10'].map(value=>({value,label:value}))]}/><button className="soft-button" onClick={()=>{setBlock('all');setDate('all');setSearch('')}}>Reset filters</button></div>{selected?<div className="recording-layout"><section className="section-card"><div className="card-heading"><div><h2>{selected.title}</h2><p>{selected.date} · {selected.time} UTC · {selected.flightId}</p></div><a className="soft-button" href={selected.source} download={`${selected.id}-demo.mp4`} aria-label="Download demo recording"><Download size={16}/></a></div><VideoPlayer key={selected.id} source={selected.source} poster={selected.poster} title={selected.title}/><div className="recording-metadata"><span>{selected.id}</span><span>{selected.drone}</span><span>Duration {selected.duration}</span></div></section><section className="section-card recording-list"><div className="card-heading"><h2>Recordings</h2><span className="count-pill">{filtered.length}</span></div>{filtered.map(c=><button key={c.id} className={'recording-item '+(selected.id===c.id?'selected':'')} onClick={()=>setSelectedId(c.id)} aria-pressed={selected.id===c.id}><div><Image unoptimized src={c.poster} alt="Synthetic solar inspection thumbnail" width={108} height={70} loading="lazy"/><span>{c.duration}</span></div><div><b>{c.title}</b><p>{c.date} · {c.time}</p><small>{c.flightId}</small></div></button>)}</section></div>:<div className="empty"><Video className="mx-auto mb-4"/><h2>No recordings match these filters</h2><p className="mt-3">Try a different block or date, or reset the filters.</p></div>}<p className="table-note">Demo recording records share one illustrative clip. Replace the sample with your own drone footage using the local preview control.</p></>;
}
