'use client';
import {useEffect,useRef,useState} from 'react';
import {Upload,RotateCcw,Video,Play} from 'lucide-react';
export default function VideoPlayer({source,poster,title,loop=false}:{source:string;poster:string;title:string;loop?:boolean}) {
  const input=useRef<HTMLInputElement>(null),video=useRef<HTMLVideoElement>(null),localUrl=useRef<string|null>(null);
  const [custom,setCustom]=useState<{url:string;name:string}|null>(null),[error,setError]=useState(''),[playing,setPlaying]=useState(false);
  useEffect(()=>()=>{if(localUrl.current)URL.revokeObjectURL(localUrl.current)},[]);
  function choose(file:File|undefined){if(!file)return;if(!file.type.startsWith('video/')){setError('Choose a video file, such as MP4 or WebM.');return;}if(localUrl.current)URL.revokeObjectURL(localUrl.current);const url=URL.createObjectURL(file);localUrl.current=url;setCustom({url,name:file.name});setError('');setPlaying(false);}
  function reset(){if(localUrl.current)URL.revokeObjectURL(localUrl.current);localUrl.current=null;setCustom(null);setError('');setPlaying(false);if(input.current)input.current.value='';}
  return <div className="video-player"><div className="video-frame"><video key={custom?.url??source} ref={video} controls playsInline preload="none" loop={loop} poster={custom?undefined:poster} aria-label={title} onPlay={()=>setPlaying(true)} onPause={()=>setPlaying(false)} onEnded={()=>setPlaying(false)} onError={()=>setError('This video could not be played. Try an MP4 with H.264 video or a WebM file.')}><source src={custom?.url??source}/>{!custom&&<track kind="captions" src="/media/demo-captions.vtt" srcLang="en" label="No speech in demo"/>}Your browser does not support video playback.</video><span className="video-source-tag"><Video size={13}/>{custom?'LOCAL VIDEO PREVIEW':'SIMULATED DEMO · SYNTHETIC IMAGE LOOP'}</span></div><div className="video-caption"><div><b>{custom?custom.name:title}</b><p>{custom?'Your file plays locally in this browser. It is not uploaded or saved.':'Illustrative clip made from a synthetic still image. No real drone feed is connected.'}</p></div><span className={'playback-state '+(playing?'playing':'')}><Play size={12}/>{playing?'Playing':'Paused'}</span></div><div className="video-file-controls"><input type="file" accept="video/*" ref={input} className="sr-only" aria-label="Choose a drone video file" onChange={e=>choose(e.target.files?.[0])}/><button className="soft-button" onClick={()=>input.current?.click()}><Upload size={15}/>Preview your drone video</button>{custom&&<button className="soft-button" onClick={reset}><RotateCcw size={14}/>Use demo clip</button>}<span>MP4 or WebM · file stays on your device</span></div>{error&&<p className="error video-error" role="alert">{error}</p>}</div>;
}
